version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/maastokartoitus-app

    steps:
      - checkout
      - restore_cache:
          key: node-v1-{{ checksum "maastokartoitus-app/package-lock.json" }}-{{ arch }}
      - run: 
          name: Install dependencies
          command: 'npm install'
      - save_cache:
          key: node-v1-{{ checksum "maastokartoitus-app/package-lock.json" }}-{{ arch }}
          paths:
            - node_modules
