export const getBirdList = async () => {
  const birdList = [
    {'vernacularName':{'fi':'kyhmyjoutsen','sv':'knölsvan','en':'Mute Swan'},'scientificName':'Cygnus olor','id':'MX.26277','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'laulujoutsen','sv':'sångsvan','en':'Whooper Swan'},'scientificName':'Cygnus cygnus','id':'MX.26280','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'sädgås','fi':'metsähanhi','en':'Bean Goose'},'scientificName':'Anser fabalis','id':'MX.26287','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kiljuhanhi','sv':'fjällgås','en':'Lesser White-fronted Goose'},'scientificName':'Anser erythropus','id':'MX.26290','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'merihanhi','sv':'grågås','en':'Greylag Goose'},'scientificName':'Anser anser','id':'MX.26291','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'kanadagås','fi':'kanadanhanhi','en':'Canada Goose'},'scientificName':'Branta canadensis','id':'MX.26298','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'valkoposkihanhi','sv':'vitkindad gås','en':'Barnacle Goose'},'scientificName':'Branta leucopsis','id':'MX.26299','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'gravand','fi':'ristisorsa','en':'Common Shelduck'},'scientificName':'Tadorna tadorna','id':'MX.26323','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'haapana','sv':'bläsand','en':'Eurasian Wigeon'},'scientificName':'Anas penelope','id':'MX.26360','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'harmaasorsa','sv':'snatterand','en':'Gadwall'},'scientificName':'Anas strepera','id':'MX.26364','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'kricka','fi':'tavi','en':'Eurasian Teal'},'scientificName':'Anas crecca','id':'MX.26366','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'sinisorsa','sv':'gräsand','en':'Mallard'},'scientificName':'Anas platyrhynchos','id':'MX.26373','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'jouhisorsa','sv':'stjärtand','en':'Northern Pintail'},'scientificName':'Anas acuta','id':'MX.26382','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'heinätavi','sv':'årta','en':'Garganey'},'scientificName':'Anas querquedula','id':'MX.26388','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'lapasorsa','sv':'skedand','en':'Northern Shoveler'},'scientificName':'Anas clypeata','id':'MX.26394','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'punasotka','sv':'brunand','en':'Common Pochard'},'scientificName':'Aythya ferina','id':'MX.26407','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'tukkasotka','sv':'vigg','en':'Tufted Duck'},'scientificName':'Aythya fuligula','id':'MX.26415','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'lapasotka','sv':'bergand','en':'Greater Scaup'},'scientificName':'Aythya marila','id':'MX.26416','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'ejder','fi':'haahka','en':'Common Eider'},'scientificName':'Somateria mollissima','id':'MX.26419','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'alli','sv':'alfågel','en':'Long-tailed Duck'},'scientificName':'Clangula hyemalis','id':'MX.26427','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'sjöorre','fi':'mustalintu','en':'Common Scoter'},'scientificName':'Melanitta nigra','id':'MX.26429','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pilkkasiipi','sv':'svärta','en':'Velvet Scoter'},'scientificName':'Melanitta fusca','id':'MX.26431','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'knipa','fi':'telkkä','en':'Common Goldeneye'},'scientificName':'Bucephala clangula','id':'MX.26435','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'uivelo','sv':'salskrake','en':'Smew'},'scientificName':'Mergellus albellus','id':'MX.26438','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'tukkakoskelo','sv':'småskrake','en':'Red-breasted Merganser'},'scientificName':'Mergus serrator','id':'MX.26440','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'isokoskelo','sv':'storskrake','en':'Common Merganser'},'scientificName':'Mergus merganser','id':'MX.26442','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'vaktel','fi':'viiriäinen','en':'Common Quail'},'scientificName':'Coturnix coturnix','id':'MX.27058','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pyy','sv':'järpe','en':'Hazel Grouse'},'scientificName':'Tetrastes bonasia','id':'MX.26931','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'riekko','sv':'dalripa','en':'Willow Ptarmigan'},'scientificName':'Lagopus lagopus','id':'MX.26921','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kiiruna','sv':'fjällripa','en':'Rock Ptarmigan'},'scientificName':'Lagopus muta','id':'MX.26922','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'teeri','sv':'orre','en':'Black Grouse'},'scientificName':'Tetrao tetrix','id':'MX.26926','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'metso','sv':'tjäder','en':'Western Capercaillie'},'scientificName':'Tetrao urogallus','id':'MX.26928','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'peltopyy','sv':'rapphöna','en':'Grey Partridge'},'scientificName':'Perdix perdix','id':'MX.27048','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'fasaani','sv':'fasan','en':'Common Pheasant'},'scientificName':'Phasianus colchicus','id':'MX.27152','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kaakkuri','sv':'smålom','en':'Red-throated Loon'},'scientificName':'Gavia stellata','id':'MX.25836','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kuikka','sv':'storlom','en':'Black-throated Loon'},'scientificName':'Gavia arctica','id':'MX.25837','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pikku-uikku','sv':'smådopping','en':'Little Grebe'},'scientificName':'Tachybaptus ruficollis','id':'MX.25844','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'silkkiuikku','sv':'skäggdopping','en':'Great Crested Grebe'},'scientificName':'Podiceps cristatus','id':'MX.25860','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'härkälintu','sv':'gråhakedopping','en':'Red-necked Grebe'},'scientificName':'Podiceps grisegena','id':'MX.25859','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'mustakurkku-uikku','sv':'svarthakedopping','en':'Horned Grebe'},'scientificName':'Podiceps auritus','id':'MX.25861','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'merimetso','sv':'storskarv','en':'Great Cormorant'},'scientificName':'Phalacrocorax carbo','id':'MX.26043','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kaulushaikara','sv':'rördrom','en':'Eurasian Bittern'},'scientificName':'Botaurus stellaris','id':'MX.26164','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'jalohaikara','sv':'ägretthäger','en':'Great Egret'},'scientificName':'Egretta alba','id':'MX.26105','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'harmaahaikara','sv':'gråhäger','en':'Grey Heron'},'scientificName':'Ardea cinerea','id':'MX.26094','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'mehiläishaukka','sv':'bivråk','en':'European Honey Buzzard'},'scientificName':'Pernis apivorus','id':'MX.26488','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'brun glada','fi':'haarahaukka','en':'Black Kite'},'scientificName':'Milvus migrans','id':'MX.26518','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'merikotka','sv':'havsörn','en':'White-tailed Sea Eagle'},'scientificName':'Haliaeetus albicilla','id':'MX.26530','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'ruskosuohaukka','sv':'brun kärrhök','en':'Western Marsh Harrier'},'scientificName':'Circus aeruginosus','id':'MX.26597','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'sinisuohaukka','sv':'blå kärrhök','en':'Hen Harrier'},'scientificName':'Circus cyaneus','id':'MX.26592','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'arosuohaukka','sv':'stäpphök','en':'Pallid Harrier'},'scientificName':'Circus macrourus','id':'MX.26594','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'niittysuohaukka','sv':'ängshök','en':'Montagus Harrier'},'scientificName':'Circus pygargus','id':'MX.26596','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kanahaukka','sv':'duvhök','en':'Northern Goshawk'},'scientificName':'Accipiter gentilis','id':'MX.26647','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'varpushaukka','sv':'sparvhök','en':'Eurasian Sparrowhawk'},'scientificName':'Accipiter nisus','id':'MX.26639','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'hiirihaukka','sv':'ormvråk','en':'Common Buzzard'},'scientificName':'Buteo buteo','id':'MX.26701','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'piekana','sv':'fjällvråk','en':'Rough-legged Buzzard'}, 'scientificName':'Buteo lagopus','id':'MX.26704','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kiljukotka','sv':'större skrikörn','en':'Greater Spotted Eagle'},'scientificName':'Aquila clanga','id':'MX.26723','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'maakotka','sv':'kungsörn','en':'Golden Eagle'},'scientificName':'Aquila chrysaetos','id':'MX.26727','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'fiskgjuse','fi':'sääksi','en':'Osprey'},'scientificName':'Pandion haliaetus','id':'MX.26472','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'tuulihaukka','sv':'tornfalk','en':'Common Kestrel'},'scientificName':'Falco tinnunculus','id':'MX.26796','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'ampuhaukka','sv':'stenfalk','en':'Merlin'},'scientificName':'Falco columbarius','id':'MX.26808','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'lärkfalk','fi':'nuolihaukka','en':'Eurasian Hobby'},'scientificName':'Falco subbuteo','id':'MX.26811','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'tunturihaukka','sv':'jaktfalk','en':'Gyrfalcon'},'scientificName':'Falco rusticolus','id':'MX.26825','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'muuttohaukka','sv':'pilgrimsfalk','en':'Peregrine Falcon'},'scientificName':'Falco peregrinus','id':'MX.26828','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'vattenrall','fi':'luhtakana','en':'Water Rail'},'scientificName':'Rallus aquaticus','id':'MX.27276','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'luhtahuitti','sv':'småfläckig sumphöna','en':'Spotted Crake'},'scientificName':'Porzana porzana','id':'MX.27345','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pikkuhuitti','sv':'mindre sumphöna','en':'Little Crake'},'scientificName':'Porzana parva','id':'MX.27342','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'ruisrääkkä','sv':'kornknarr','en':'Corn Crake'},'scientificName':'Crex crex','id':'MX.27328','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'liejukana','sv':'rörhöna','en':'Common Moorhen'},'scientificName':'Gallinula chloropus','id':'MX.27364','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'nokikana','sv':'sothöna','en':'Eurasian Coot'},'scientificName':'Fulica atra','id':'MX.27381','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kurki','sv':'trana','en':'Common Crane'},'scientificName':'Grus grus','id':'MX.27214','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'meriharakka','sv':'strandskata','en':'Eurasian Oystercatcher'},'scientificName':'Haematopus ostralegus','id':'MX.27459','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kapustarinta','sv':'ljungpipare','en':'European Golden Plover'},'scientificName':'Pluvialis apricaria','id':'MX.27553','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'töyhtöhyyppä','sv':'tofsvipa','en':'Northern Lapwing'},'scientificName':'Vanellus vanellus','id':'MX.27527','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pikkutylli','sv':'mindre strandpipare','en':'Little Ringed Plover'},'scientificName':'Charadrius dubius','id':'MX.27562','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'tylli','sv':'större strandpipare','en':'Common Ringed Plover'},'scientificName':'Charadrius hiaticula','id':'MX.27559','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'keräkurmitsa','sv':'fjällpipare','en':'Eurasian Dotterel'},'scientificName':'Charadrius morinellus','id':'MX.27597','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pikkukuovi','sv':'småspov','en':'Whimbrel'},'scientificName':'Numenius phaeopus','id':'MX.27610','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kuovi','sv':'storspov','en':'Eurasian Curlew'},'scientificName':'Numenius arquata','id':'MX.27613','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'mustapyrstökuiri','sv':'rödspov','en':'Black-tailed Godwit'},'scientificName':'Limosa limosa','id':'MX.27603','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'punakuiri','sv':'myrspov','en':'Bar-tailed Godwit'},'scientificName':'Limosa lapponica','id':'MX.27605','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'karikukko','sv':'roskarl','en':'Ruddy Turnstone'},'scientificName':'Arenaria interpres','id':'MX.27642','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'suokukko','sv':'brushane','en':'Ruff'},'scientificName':'Calidris pugnax','id':'MX.27710','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'jänkäsirriäinen','sv':'myrsnäppa','en':'Broad-billed Sandpiper'},'scientificName':'Calidris falcinellus','id':'MX.27704','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'lapinsirri','sv':'mosnäppa','en':'Temmincks Stint'},'scientificName':'Calidris temminckii','id':'MX.27689','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'suosirri','sv':'kärrsnäppa','en':'Dunlin'},'scientificName':'Calidris alpina','id':'MX.27699','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'merisirri','sv':'skärsnäppa','en':'Purple Sandpiper'},'scientificName':'Calidris maritima','id':'MX.27697','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pikkusirri','sv':'småsnäppa','en':'Little Stint'},'scientificName':'Calidris minuta','id':'MX.27688','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'vesipääsky','sv':'smalnäbbad simsnäppa','en':'Red-necked Phalarope'},'scientificName':'Phalaropus lobatus','id':'MX.27646','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'rantakurvi','sv':'tereksnäppa','en':'Terek Sandpiper'},'scientificName':'Xenus cinereus','id':'MX.27632','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'rantasipi','sv':'drillsnäppa','en':'Common Sandpiper'},'scientificName':'Actitis hypoleucos','id':'MX.27634','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'metsäviklo','sv':'skogssnäppa','en':'Green Sandpiper'},'scientificName':'Tringa ochropus','id':'MX.27626','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'mustaviklo','sv':'svartsnäppa','en':'Spotted Redshank'},'scientificName':'Tringa erythropus','id':'MX.27619','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'gluttsnäppa','fi':'valkoviklo','en':'Common Greenshank'},'scientificName':'Tringa nebularia','id':'MX.27622','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'lampiviklo','sv':'dammsnäppa','en':'Marsh Sandpiper'},'scientificName':'Tringa stagnatilis','id':'MX.27621','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'liro','sv':'grönbena','en':'Wood Sandpiper'},'scientificName':'Tringa glareola','id':'MX.27628','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'rödbena','fi':'punajalkaviklo','en':'Common Redshank'},'scientificName':'Tringa totanus','id':'MX.27620','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'jänkäkurppa','sv':'Dvärgbeckasin','en':'Jack Snipe'},'scientificName':'Lymnocryptes minimus','id':'MX.27674','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'lehtokurppa','sv':'morkulla','en':'Eurasian Woodcock'},'scientificName':'Scolopax rusticola','id':'MX.27649','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'taivaanvuohi','sv':'enkelbeckasin','en':'Common Snipe'},'scientificName':'Gallinago gallinago','id':'MX.27666','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'heinäkurppa','sv':'dubbelbeckasin','en':'Great Snipe'},'scientificName':'Gallinago media','id':'MX.27665','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'merikihu','sv':'kustlabb','en':'Parasitic Jaeger'},'scientificName':'Stercorarius parasiticus','id':'MX.27730','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'tunturikihu','sv':'fjällabb','en':'Long-tailed Jaeger'},'scientificName':'Stercorarius longicaudus','id':'MX.27731','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'riskilä','sv':'tobisgrissla','en':'Black Guillemot'},'scientificName':'Cepphus grylle','id':'MX.27855','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'ruokki','sv':'tordmule','en':'Razorbill'},'scientificName':'Alca torda','id':'MX.27850','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'etelänkiisla','sv':'sillgrissla','en':'Common Murre'},'scientificName':'Uria aalge','id':'MX.27853','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pikkutiira','sv':'småtärna','en':'Little Tern'},'scientificName':'Sternula albifrons','id':'MX.27821','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'räyskä','sv':'skräntärna','en':'Caspian Tern'},'scientificName':'Hydroprogne caspia','id':'MX.27797','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'svarttärna','fi':'mustatiira','en':'Black Tern'},'scientificName':'Chlidonias niger','id':'MX.27791','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kalatiira','sv':'fisktärna','en':'Common Tern'},'scientificName':'Sterna hirundo','id':'MX.27801','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'lapintiira','sv':'silvertärna','en':'Arctic Tern'},'scientificName':'Sterna paradisaea','id':'MX.27802','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pikkulokki','sv':'dvärgmås','en':'Little Gull'},'scientificName':'Hydrocoloeus minutus','id':'MX.27777','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'naurulokki','sv':'skrattmås','en':'Black-headed Gull'},'scientificName':'Larus ridibundus','id':'MX.27774','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kalalokki','sv':'fiskmås','en':'Mew Gull'},'scientificName':'Larus canus','id':'MX.27748','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'selkälokki','sv':'silltrut','en':'Lesser Black-backed Gull'},'scientificName':'Larus fuscus','id':'MX.27753','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'harmaalokki','sv':'gråtrut','en':'European Herring Gull'},'scientificName':'Larus argentatus','id':'MX.27750','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'merilokki','sv':'havstrut','en':'Great Black-backed Gull'},'scientificName':'Larus marinus','id':'MX.27759','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kalliokyyhky','sv':'klippduva','en':'Rock Dove'},'scientificName':'Columba livia','id':'MX.27903','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'uuttukyyhky','sv':'skogsduva','en':'Stock Dove'},'scientificName':'Columba oenas','id':'MX.27908','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'sepelkyyhky','sv':'ringduva','en':'Common Wood Pigeon'},'scientificName':'Columba palumbus','id':'MX.27911','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'turkinkyyhky','sv':'turkduva','en':'Eurasian Collared Dove'},'scientificName':'Streptopelia decaocto','id':'MX.27960','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'turturikyyhky','sv':'turturduva','en':'European Turtle Dove'},'scientificName':'Streptopelia turtur','id':'MX.27955','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'käki','sv':'gök','en':'Common Cuckoo'},'scientificName':'Cuculus canorus','id':'MX.28715','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'se':'lidnu','fi':'huuhkaja','sv':'berguv','en':'Eurasian Eagle-owl'},'scientificName':'Bubo bubo','id':'MX.28965','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'tunturipöllö','sv':'fjälluggla','en':'Snowy Owl'},'scientificName':'Bubo scandiacus','id':'MX.28987','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'hiiripöllö','sv':'hökuggla','en':'Northern Hawk-Owl'},'scientificName':'Surnia ulula','id':'MX.29008','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'varpuspöllö','sv':'sparvuggla','en':'Eurasian Pygmy Owl'},'scientificName':'Glaucidium passerinum','id':'MX.29011','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'lehtopöllö','sv':'kattuggla','en':'Tawny Owl'},'scientificName':'Strix aluco','id':'MX.28998','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'slaguggla','fi':'viirupöllö','en':'Ural Owl'},'scientificName':'Strix uralensis','id':'MX.29003','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'lapinpöllö','sv':'lappuggla','en':'Great Grey Owl'},'scientificName':'Strix nebulosa','id':'MX.29004','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'sarvipöllö','sv':'hornuggla','en':'Long-eared Owl'},'scientificName':'Asio otus','id':'MX.29068','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'suopöllö','sv':'jorduggla','en':'Short-eared Owl'},'scientificName':'Asio flammeus','id':'MX.29072','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'helmipöllö','sv':'pärluggla','en':'Boreal Owl'},'scientificName':'Aegolius funereus','id':'MX.29038','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kehrääjä','sv':'nattskärra','en':'European Nightjar'},'scientificName':'Caprimulgus europaeus','id':'MX.29172','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'tervapääsky','sv':'tornseglare','en':'Common Swift'},'scientificName':'Apus apus','id':'MX.29324','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kuningaskalastaja','sv':'kungsfiskare','en':'Common Kingfisher'},'scientificName':'Alcedo atthis','id':'MX.29860','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'göktyta','fi':'käenpiika','en':'Eurasian Wryneck'},'scientificName':'Jynx torquilla','id':'MX.30333','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'harmaapäätikka','sv':'gråspett','en':'Grey-headed Woodpecker'},'scientificName':'Picus canus','id':'MX.30530','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'palokärki','sv':'spillkråka','en':'Black Woodpecker'},'scientificName':'Dryocopus martius','id':'MX.30504','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'käpytikka','sv':'större hackspett','en':'Great Spotted Woodpecker'},'scientificName':'Dendrocopos major','id':'MX.30443','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'valkoselkätikka','sv':'vitryggig hackspett','en':'White-backed Woodpecker'},'scientificName':'Dendrocopos leucotos','id':'MX.30438','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pikkutikka','sv':'mindre hackspett','en':'Lesser Spotted Woodpecker'},'scientificName':'Dendrocopos minor','id':'MX.30428','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pohjantikka','sv':'tretåig hackspett','en':'Eurasian Three-toed Woodpecker'},'scientificName':'Picoides tridactylus','id':'MX.30453','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kangaskiuru','sv':'trädlärka','en':'Woodlark'},'scientificName':'Lullula arborea','id':'MX.32063','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kiuru','sv':'sånglärka','en':'Eurasian Skylark'},'scientificName':'Alauda arvensis','id':'MX.32065','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'tunturikiuru','sv':'berglärka','en':'Horned Lark'},'scientificName':'Eremophila alpestris','id':'MX.32076','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'backsvala','fi':'törmäpääsky','en':'Sand Martin'},'scientificName':'Riparia riparia','id':'MX.32120','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'haarapääsky','sv':'ladusvala','en':'Barn Swallow'},'scientificName':'Hirundo rustica','id':'MX.32132','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'räystäspääsky','sv':'hussvala','en':'Common House Martin'},'scientificName':'Delichon urbicum','id':'MX.32163','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'nummikirvinen','sv':'fältpiplärka','en':'Tawny Pipit'},'scientificName':'Anthus campestris','id':'MX.32207','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'trädpiplärka','fi':'metsäkirvinen','en':'Tree Pipit'},'scientificName':'Anthus trivialis','id':'MX.32214','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'niittykirvinen','sv':'ängspiplärka','en':'Meadow Pipit'},'scientificName':'Anthus pratensis','id':'MX.32213','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'lapinkirvinen','sv':'rödstrupig piplärka','en':'Red-throated Pipit'},'scientificName':'Anthus cervinus','id':'MX.32217','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'luotokirvinen','sv':'skärpiplärka','en':'Eurasian Rock Pipit'},'scientificName':'Anthus petrosus','id':'MX.32221','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'keltavästäräkki','sv':'gulärla','en':'Western Yellow Wagtail'},'scientificName':'Motacilla flava','id':'MX.32180','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'sitruunavästäräkki','sv':'citronärla','en':'Citrine Wagtail'},'scientificName':'Motacilla citreola','id':'MX.32181','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'virtavästäräkki','sv':'forsärla','en':'Grey Wagtail'},'scientificName':'Motacilla cinerea','id':'MX.32182','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'västäräkki','sv':'sädesärla','en':'White Wagtail'},'scientificName':'Motacilla alba','id':'MX.32183','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'tilhi','sv':'sidensvans','en':'Bohemian Waxwing'},'scientificName':'Bombycilla garrulus','id':'MX.32608','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'koskikara','sv':'strömstare','en':'White-throated Dipper'},'scientificName':'Cinclus cinclus','id':'MX.32625','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'peukaloinen','sv':'gärdsmyg','en':'Eurasian Wren'},'scientificName':'Troglodytes troglodytes','id':'MX.32696','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'rautiainen','sv':'järnsparv','en':'Dunnock'},'scientificName':'Prunella modularis','id':'MX.32772','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'punarinta','sv':'rödhake','en':'European Robin'},'scientificName':'Erithacus rubecula','id':'MX.32801','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'näktergal','fi':'satakieli','en':'Thrush Nightingale'},'scientificName':'Luscinia luscinia','id':'MX.32819','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'sinirinta','sv':'blåhake','en':'Bluethroat'},'scientificName':'Luscinia svecica','id':'MX.32821','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'sinipyrstö','sv':'blåstjärt','en':'Red-flanked Bluetail'},'scientificName':'Tarsiger cyanurus','id':'MX.32816','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'svart rödstjärt','fi':'mustaleppälintu','en':'Black Redstart'},'scientificName':'Phoenicurus ochruros','id':'MX.32894','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'leppälintu','sv':'rödstjärt','en':'Common Redstart'},'scientificName':'Phoenicurus phoenicurus','id':'MX.32895','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pensastasku','sv':'buskskvätta','en':'Whinchat'},'scientificName':'Saxicola rubetra','id':'MX.32949','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'vitgumpad buskskvätta','fi':'sepeltasku','en':'Siberian Stonechat'},'scientificName':'Saxicola maurus','id':'MX.200001','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kivitasku','sv':'stenskvätta','en':'Northern Wheatear'},'scientificName':'Oenanthe oenanthe','id':'MX.32966','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'sepelrastas','sv':'ringtrast','en':'Ring Ouzel'},'scientificName':'Turdus torquatus','id':'MX.33104','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'mustarastas','sv':'koltrast','en':'Common Blackbird'},'scientificName':'Turdus merula','id':'MX.33106','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'räkättirastas','sv':'björktrast','en':'Fieldfare'},'scientificName':'Turdus pilaris','id':'MX.33117','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'taltrast','fi':'laulurastas','en':'Song Thrush'},'scientificName':'Turdus philomelos','id':'MX.33119','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'rödvingetrast','fi':'punakylkirastas','en':'Redwing'},'scientificName':'Turdus iliacus','id':'MX.33118','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kulorastas','sv':'dubbeltrast','en':'Mistle Thrush'},'scientificName':'Turdus viscivorus','id':'MX.33121','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pensassirkkalintu','sv':'gräshoppsångare','en':'Common Grasshopper Warbler'},'scientificName':'Locustella naevia','id':'MX.33630','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'viitasirkkalintu','sv':'flodsångare','en':'River Warbler'},'scientificName':'Locustella fluviatilis','id':'MX.33634','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'ruokosirkkalintu','sv':'vassångare','en':'Savis Warbler'},'scientificName':'Locustella luscinioides','id':'MX.33635','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pikkukultarinta','sv':'stäppsångare','en':'Booted Warbler'},'scientificName':'Iduna caligata','id':'MX.33671','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kultarinta','sv':'härmsångare','en':'Icterine Warbler'},'scientificName':'Hippolais icterina','id':'MX.33676','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'sävsångare','fi':'ruokokerttunen','en':'Sedge Warbler'},'scientificName':'Acrocephalus schoenobaenus','id':'MX.33641','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'viitakerttunen','sv':'busksångare','en':'Blyths Reed Warbler'},'scientificName':'Acrocephalus dumetorum','id':'MX.33650','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'luhtakerttunen','sv':'kärrsångare','en':'Marsh Warbler'},'scientificName':'Acrocephalus palustris','id':'MX.33649','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'rytikerttunen','sv':'rörsångare','en':'Common Reed Warbler'},'scientificName':'Acrocephalus scirpaceus','id':'MX.33646','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'rastaskerttunen','sv':'trastsångare','en':'Great Reed Warbler'},'scientificName':'Acrocephalus arundinaceus','id':'MX.33651','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kirjokerttu','sv':'höksångare','en':'Barred Warbler'},'scientificName':'Sylvia nisoria','id':'MX.33939','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'hernekerttu','sv':'ärtsångare','en':'Lesser Whitethroat'},'scientificName':'Sylvia curruca','id':'MX.33937','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pensaskerttu','sv':'törnsångare','en':'Common Whitethroat'},'scientificName':'Sylvia communis','id':'MX.33936','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'lehtokerttu','sv':'trädgårdssångare','en':'Garden Warbler'},'scientificName':'Sylvia borin','id':'MX.33935','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'mustapääkerttu','sv':'svarthätta','en':'Eurasian Blackcap'},'scientificName':'Sylvia atricapilla','id':'MX.33934','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'idänuunilintu','sv':'lundsångare','en':'Greenish Warbler'},'scientificName':'Phylloscopus trochiloides','id':'MX.33891','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'lapinuunilintu','sv':'nordsångare','en':'Arctic Warbler'},'scientificName':'Phylloscopus borealis','id':'MX.33890','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'sirittäjä','sv':'grönsångare','en':'Wood Warbler'},'scientificName':'Phylloscopus sibilatrix','id':'MX.33878','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'tiltaltti','sv':'gransångare','en':'Common Chiffchaff'},'scientificName':'Phylloscopus collybita','id':'MX.33874','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pajulintu','sv':'lövsångare','en':'Willow Warbler'},'scientificName':'Phylloscopus trochilus','id':'MX.33873','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'hippiäinen','sv':'kungsfågel','en':'Goldcrest'},'scientificName':'Regulus regulus','id':'MX.33954','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'tulipäähippiäinen','sv':'brandkronad kungsfågel','en':'Common Firecrest'},'scientificName':'Regulus ignicapilla','id':'MX.33952','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'harmaasieppo','sv':'grå flugsnappare','en':'Spotted Flycatcher'},'scientificName':'Muscicapa striata','id':'MX.33989','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pikkusieppo','sv':'mindre flugsnappare','en':'Red-breasted Flycatcher'},'scientificName':'Ficedula parva','id':'MX.34029','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'svartvit flugsnappare','fi':'kirjosieppo','en':'European Pied Flycatcher'},'scientificName':'Ficedula hypoleuca','id':'MX.34021','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'viiksitimali','sv':'skäggmes','en':'Bearded Reedling'},'scientificName':'Panurus biarmicus','id':'MX.33492','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pyrstötiainen','sv':'stjärtmes','en':'Long-tailed Tit'},'scientificName':'Aegithalos caudatus','id':'MX.34505','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'sinitiainen','sv':'blåmes','en':'Eurasian Blue Tit'},'scientificName':'Cyanistes caeruleus','id':'MX.34574','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'talitiainen','sv':'talgoxe','en':'Great Tit'},'scientificName':'Parus major','id':'MX.34567','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'svartmes','fi':'kuusitiainen','en':'Coal Tit'},'scientificName':'Periparus ater','id':'MX.34549','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'töyhtötiainen','sv':'tofsmes','en':'European Crested Tit'},'scientificName':'Lophophanes cristatus','id':'MX.34553','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'hömötiainen','sv':'talltita','en':'Willow Tit'},'scientificName':'Poecile montanus','id':'MX.34535','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'lapintiainen','sv':'lappmes','en':'Siberian Tit'},'scientificName':'Poecile cinctus','id':'MX.34542','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pähkinänakkeli','sv':'nötväcka','en':'Eurasian Nuthatch'},'scientificName':'Sitta europaea','id':'MX.34586','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'puukiipijä','sv':'trädkrypare','en':'Eurasian Treecreeper'},'scientificName':'Certhia familiaris','id':'MX.34616','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pussitiainen','sv':'pungmes','en':'Eurasian Penduline Tit'},'scientificName':'Remiz pendulinus','id':'MX.34517','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'sommargylling','fi':'kuhankeittäjä','en':'Eurasian Golden Oriole'},'scientificName':'Oriolus oriolus','id':'MX.36871','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pikkulepinkäinen','sv':'törnskata','en':'Red-backed Shrike'},'scientificName':'Lanius collurio','id':'MX.32561','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'isolepinkäinen','sv':'varfågel','en':'Great Grey Shrike'},'scientificName':'Lanius excubitor','id':'MX.32570','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'närhi','sv':'nötskrika','en':'Eurasian Jay'},'scientificName':'Garrulus glandarius','id':'MX.37090','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kuukkeli','sv':'lavskrika','en':'Siberian Jay'},'scientificName':'Perisoreus infaustus','id':'MX.37095','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'harakka','sv':'skata','en':'Eurasian Magpie'},'scientificName':'Pica pica','id':'MX.37122','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pähkinähakki','sv':'nötkråka','en':'Spotted Nutcracker'},'scientificName':'Nucifraga caryocatactes','id':'MX.37135','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'naakka','sv':'kaja','en':'Western Jackdaw'},'scientificName':'Corvus monedula','id':'MX.37142','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'mustavaris','sv':'råka','en':'Rook'},'scientificName':'Corvus frugilegus','id':'MX.37156','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'varis','sv':'kråka','en':'Carrion Crow'},'scientificName':'Corvus corone','id':'MX.73566','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'korppi','sv':'korp','en':'Northern Raven'},'scientificName':'Corvus corax','id':'MX.37178','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kottarainen','sv':'stare','en':'Common Starling'},'scientificName':'Sturnus vulgaris','id':'MX.36817','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'gråsparv','fi':'varpunen','en':'House Sparrow'},'scientificName':'Passer domesticus','id':'MX.36573','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'pilfink','fi':'pikkuvarpunen','en':'Eurasian Tree Sparrow'},'scientificName':'Passer montanus','id':'MX.36589','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'peippo','sv':'bofink','en':'Common Chaffinch'},'scientificName':'Fringilla coelebs','id':'MX.36237','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'järripeippo','sv':'bergfink','en':'Brambling'},'scientificName':'Fringilla montifringilla','id':'MX.36239','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'gulhämpling','fi':'keltahemppo','en':'European Serin'},'scientificName':'Serinus serinus','id':'MX.36242','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'viherpeippo','sv':'grönfink','en':'European Greenfinch'},'scientificName':'Carduelis chloris','id':'MX.36283','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'tikli','sv':'steglits','en':'European Goldfinch'},'scientificName':'Carduelis carduelis','id':'MX.36306','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'vihervarpunen','sv':'grönsiska','en':'Eurasian Siskin'},'scientificName':'Carduelis spinus','id':'MX.36287','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'hemppo','sv':'hämpling','en':'Common Linnet'},'scientificName':'Carduelis cannabina','id':'MX.36310','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'vuorihemppo','sv':'Vinterhämpling','en':'Twite'},'scientificName':'Carduelis flavirostris','id':'MX.36309','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'urpiainen','sv':'gråsiska','en':'Common Redpoll'},'scientificName':'Carduelis flammea','id':'MX.36308','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'snösiska','fi':'tundraurpiainen','en':'Arctic Redpoll'},'scientificName':'Carduelis hornemanni','id':'MX.73545','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'kirjosiipikäpylintu','sv':'bändelkorsnäbb','en':'Two-barred Crossbill'},'scientificName':'Loxia leucoptera','id':'MX.36359','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pikkukäpylintu','sv':'mindre korsnäbb','en':'Red Crossbill'},'scientificName':'Loxia curvirostra','id':'MX.36358','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'isokäpylintu','sv':'större korsnäbb','en':'Parrot Crossbill'},'scientificName':'Loxia pytyopsittacus','id':'MX.36356','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'rosenfink','fi':'punavarpunen','en':'Common Rosefinch'},'scientificName':'Carpodacus erythrinus','id':'MX.36331','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'taviokuurna','sv':'tallbit','en':'Pine Grosbeak'},'scientificName':'Pinicola enucleator','id':'MX.36351','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'punatulkku','sv':'domherre','en':'Eurasian Bullfinch'},'scientificName':'Pyrrhula pyrrhula','id':'MX.36366','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'nokkavarpunen','sv':'stenknäck','en':'Hawfinch'},'scientificName':'Coccothraustes coccothraustes','id':'MX.36368','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'lapinsirkku','sv':'lappsparv','en':'Lapland Longspur'},'scientificName':'Calcarius lapponicus','id':'MX.35185','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pulmunen','sv':'snösparv','en':'Snow Bunting'},'scientificName':'Plectrophenax nivalis','id':'MX.35189','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'keltasirkku','sv':'gulsparv','en':'Yellowhammer'},'scientificName':'Emberiza citrinella','id':'MX.35146','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'peltosirkku','sv':'ortolansparv','en':'Ortolan Bunting'},'scientificName':'Emberiza hortulana','id':'MX.35154','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pohjansirkku','sv':'videsparv','en':'Rustic Bunting'},'scientificName':'Emberiza rustica','id':'MX.35167','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'fi':'pikkusirkku','sv':'dvärgsparv','en':'Little Bunting'},'scientificName':'Emberiza pusilla','id':'MX.35165','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'},
    {'vernacularName':{'sv':'sävsparv','fi':'pajusirkku','en':'Common Reed Bunting'},'scientificName':'Emberiza schoeniclus','id':'MX.35182','intellectualRights':'MZ.intellectualRightsCC-BY-4.0'}
  ]

  return birdList
}

export const getGridName = async (gridId: string) => {
  return {
    'activityCategory': {
      'key': 'MY.atlasActivityCategoryEnum4',
      'value': 'Hyvä',
    },
    'atlas': 4,
    'atlasClassSum': 285,
    'birdAssociationArea': {
      'key': 'ML.1091',
      'value': 'Helsingin Seudun Lintutieteellinen Yhdistys - Tringa r.y.',
    },
    'coordinates': '668:339',
    'id': 'http://tun.fi/YKJ.668:339',
    'level1': 1,
    'level2': 113.60000000000001,
    'level3': 205.20000000000002,
    'level4': 259.2,
    'level5': 295.2,
    'name': 'Vantaa, Hakunila',
    'speciesCount': 117,
  }
}