
export const sendImages = async (formDataBody: FormData, token: string) => {
  return {
    'config': {
      'adapter': [],
      'data': {
        '_parts': [
          [
            'data',
            {
              'name': 'c85d3673-c000-4c3c-b24d-cf6f1cea98a6.jpg',
              'size': 4605708,
              'type': 'image/jpeg',
              'uri': 'file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252FMobile-Vihko-f12a92bd-81fd-4995-b2fd-d4b5bc8ae35b/ImagePicker/c85d3673-c000-4c3c-b24d-cf6f1cea98a6.jpg',
            },
          ],
        ],
      },
      'headers': {
        'Accept': 'application/json, text/plain, */*',
      },
      'maxBodyLength': -1,
      'maxContentLength': -1,
      'method': 'post',
      'params': {
        'access_token': 't4N06QPrUdoidv4uxVnNSeWDy9KlAIMXTOslCalPNRxwcUMi0AvCBsvS8HRYr186',
        'personToken': 'Pfk3NA3n6tXMSY6QJMFdWw5w2e8jvlqkiMnpqP0IEJdlgw7m',
      },
      'timeout': 0,
      'transformRequest': [
        [],
      ],
      'transformResponse': [
        [],
      ],
      'transitional': {
        'clarifyTimeoutError': false,
        'forcedJSONParsing': true,
        'silentJSONParsing': true,
      },
      'url': 'https://apitest.laji.fi/v0/images',
      'validateStatus': [],
      'xsrfCookieName': 'XSRF-TOKEN',
      'xsrfHeaderName': 'X-XSRF-TOKEN',
    },
    'data': [
      {
        'expires': 1657802586,
        'filename': 'c85d3673-c000-4c3c-b24d-cf6f1cea98a6.jpg',
        'id': 'be9e6b12-0e74-4397-b9f1-1c99d832a1a8',
        'name': 'data',
      },
    ],
    'headers': {
      'access-control-allow-credentials': 'true',
      'access-control-allow-origin': '*',
      'cache-control': 'public',
      'content-type': 'application/json',
      'date': 'Thu, 14 Jul 2022 12:28:08 GMT',
      'referrer-policy': 'no-referrer-when-downgrade',
      'strict-transport-security': 'max-age=31536000;includeSubDomains;preload',
      'vary': 'Accept-Encoding,User-Agent',
      'via': '1.1 fmnh-ws-test.it.helsinki.fi',
      'x-content-type-options': 'nosniff',
      'x-download-options': 'noopen',
      'x-frame-options': 'DENY',
      'x-xss-protection': '1;mode=block',
    },
    'request': {
      'DONE': 4,
      'HEADERS_RECEIVED': 2,
      'LOADING': 3,
      'OPENED': 1,
      'UNSENT': 0,
      '_aborted': false,
      '_cachedResponse': undefined,
      '_hasError': false,
      '_headers': {
        'accept': 'application/json, text/plain, */*',
      },
      '_incrementalEvents': false,
      '_lowerCaseResponseHeaders': {
        'access-control-allow-credentials': 'true',
        'access-control-allow-origin': '*',
        'cache-control': 'public',
        'content-type': 'application/json',
        'date': 'Thu, 14 Jul 2022 12:28:08 GMT',
        'referrer-policy': 'no-referrer-when-downgrade',
        'strict-transport-security': 'max-age=31536000;includeSubDomains;preload',
        'vary': 'Accept-Encoding,User-Agent',
        'via': '1.1 fmnh-ws-test.it.helsinki.fi',
        'x-content-type-options': 'nosniff',
        'x-download-options': 'noopen',
        'x-frame-options': 'DENY',
        'x-xss-protection': '1;mode=block',
      },
      '_method': 'POST',
      '_perfKey': 'network_XMLHttpRequest_https://apitest.laji.fi/v0/images?personToken=Pfk3NA3n6tXMSY6QJMFdWw5w2e8jvlqkiMnpqP0IEJdlgw7m&access_token=t4N06QPrUdoidv4uxVnNSeWDy9KlAIMXTOslCalPNRxwcUMi0AvCBsvS8HRYr186',
      '_performanceLogger': {
        '_closed': false,
        '_extras': {},
        '_pointExtras': {},
        '_points': {
          'initializeCore_end': 1657801562023,
          'initializeCore_start': 1657801561960,
        },
        '_timespans': {
          'network_XMLHttpRequest_http://8i-kzw.anonymous.mobile-vihko-app.exp.direct:80/logs': {
            'endExtras': undefined,
            'endTime': 1657801563966,
            'startExtras': undefined,
            'startTime': 1657801563089,
            'totalTime': 877,
          },
          'network_XMLHttpRequest_http://8i-kzw.anonymous.mobile-vihko-app.exp.direct:80/symbolicate': {
            'endExtras': undefined,
            'endTime': 1657801563456,
            'startExtras': undefined,
            'startTime': 1657801562922,
            'totalTime': 534,
          },
          'network_XMLHttpRequest_https://apitest.laji.fi/v0/autocomplete/taxon?q=v&lang=fi&limit=5&includePayload=true&matchType=exact,partial&includeHidden=false&excludeNameTypes=MX.hasMisappliedName,MX.hasMisspelledName,MX.hasUncertainSynonym,MX.hasOrthographicVariant&access_token=t4N06QPrUdoidv4uxVnNSeWDy9KlAIMXTOslCalPNRxwcUMi0AvCBsvS8HRYr186': {
            'endExtras': undefined,
            'endTime': 1657801618814,
            'startExtras': undefined,
            'startTime': 1657801618430,
            'totalTime': 384,
          },
          'network_XMLHttpRequest_https://apitest.laji.fi/v0/autocomplete/taxon?q=varis&lang=fi&limit=5&includePayload=true&matchType=exact,partial&includeHidden=false&excludeNameTypes=MX.hasMisappliedName,MX.hasMisspelledName,MX.hasUncertainSynonym,MX.hasOrthographicVariant&access_token=t4N06QPrUdoidv4uxVnNSeWDy9KlAIMXTOslCalPNRxwcUMi0AvCBsvS8HRYr186': {
            'endExtras': undefined,
            'endTime': 1657801620489,
            'startExtras': undefined,
            'startTime': 1657801620090,
            'totalTime': 399,
          },
          'network_XMLHttpRequest_https://apitest.laji.fi/v0/coordinates/location?lang=fi&access_token=t4N06QPrUdoidv4uxVnNSeWDy9KlAIMXTOslCalPNRxwcUMi0AvCBsvS8HRYr186': {
            'endExtras': undefined,
            'endTime': 1657801682609,
            'startExtras': undefined,
            'startTime': 1657801679594,
            'totalTime': 3015,
          },
          'network_XMLHttpRequest_https://apitest.laji.fi/v0/formPermissions?personToken=Pfk3NA3n6tXMSY6QJMFdWw5w2e8jvlqkiMnpqP0IEJdlgw7m&access_token=t4N06QPrUdoidv4uxVnNSeWDy9KlAIMXTOslCalPNRxwcUMi0AvCBsvS8HRYr186': {
            'endExtras': undefined,
            'endTime': 1657801565910,
            'startExtras': undefined,
            'startTime': 1657801565575,
            'totalTime': 335,
          },
          'network_XMLHttpRequest_https://apitest.laji.fi/v0/graphql': {
            'endExtras': undefined,
            'endTime': 1657801563769,
            'startExtras': undefined,
            'startTime': 1657801563522,
            'totalTime': 247,
          },
          'network_XMLHttpRequest_https://apitest.laji.fi/v0/images?personToken=Pfk3NA3n6tXMSY6QJMFdWw5w2e8jvlqkiMnpqP0IEJdlgw7m&access_token=t4N06QPrUdoidv4uxVnNSeWDy9KlAIMXTOslCalPNRxwcUMi0AvCBsvS8HRYr186': {
            'endExtras': undefined,
            'endTime': 1657801688472,
            'startExtras': undefined,
            'startTime': 1657801682627,
            'totalTime': 5845,
          },
          'network_XMLHttpRequest_https://apitest.laji.fi/v0/named-places?collectionID=HR.2951&includePublic=true&includeUnits=false&access_token=t4N06QPrUdoidv4uxVnNSeWDy9KlAIMXTOslCalPNRxwcUMi0AvCBsvS8HRYr186&pageSize=1000': {
            'endExtras': undefined,
            'endTime': 1657801563479,
            'startExtras': undefined,
            'startTime': 1657801563145,
            'totalTime': 334,
          },
          'network_XMLHttpRequest_https://apitest.laji.fi/v0/person-token//Pfk3NA3n6tXMSY6QJMFdWw5w2e8jvlqkiMnpqP0IEJdlgw7m?access_token=t4N06QPrUdoidv4uxVnNSeWDy9KlAIMXTOslCalPNRxwcUMi0AvCBsvS8HRYr186': {
            'endExtras': undefined,
            'endTime': 1657801610899,
            'startExtras': undefined,
            'startTime': 1657801610532,
            'totalTime': 367,
          },
          'network_XMLHttpRequest_https://apitest.laji.fi/v0/person//Pfk3NA3n6tXMSY6QJMFdWw5w2e8jvlqkiMnpqP0IEJdlgw7m/profile?access_token=t4N06QPrUdoidv4uxVnNSeWDy9KlAIMXTOslCalPNRxwcUMi0AvCBsvS8HRYr186': {
            'endExtras': undefined,
            'endTime': 1657801566193,
            'startExtras': undefined,
            'startTime': 1657801566011,
            'totalTime': 182,
          },
          'network_XMLHttpRequest_https://cdn.laji.fi/mobiilivihko/version.txt': {
            'endExtras': undefined,
            'endTime': 1657801566872,
            'startExtras': undefined,
            'startTime': 1657801566437,
            'totalTime': 435,
          },
        },
      },
      '_requestId': null,
      '_response': '[{"name":"data","filename":"c85d3673-c000-4c3c-b24d-cf6f1cea98a6.jpg","id":"be9e6b12-0e74-4397-b9f1-1c99d832a1a8","expires":1657802586}]',
      '_responseType': '',
      '_sent': true,
      '_subscriptions': [],
      '_timedOut': false,
      '_trackingName': 'unknown',
      '_url': 'https://apitest.laji.fi/v0/images?personToken=Pfk3NA3n6tXMSY6QJMFdWw5w2e8jvlqkiMnpqP0IEJdlgw7m&access_token=t4N06QPrUdoidv4uxVnNSeWDy9KlAIMXTOslCalPNRxwcUMi0AvCBsvS8HRYr186',
      'readyState': 4,
      'responseHeaders': {
        'Access-Control-Allow-Credentials': 'true',
        'Access-Control-Allow-Origin': '*',
        'Cache-Control': 'public',
        'Content-Type': 'application/json',
        'Date': 'Thu, 14 Jul 2022 12:28:08 GMT',
        'Referrer-Policy': 'no-referrer-when-downgrade',
        'Strict-Transport-Security': 'max-age=31536000;includeSubDomains;preload',
        'Vary': 'Accept-Encoding,User-Agent',
        'X-Content-Type-Options': 'nosniff',
        'X-Download-Options': 'noopen',
        'X-Frame-Options': 'DENY',
        'X-XSS-Protection': '1;mode=block',
        'via': '1.1 fmnh-ws-test.it.helsinki.fi',
      },
      'responseURL': 'https://apitest.laji.fi/v0/images?personToken=Pfk3NA3n6tXMSY6QJMFdWw5w2e8jvlqkiMnpqP0IEJdlgw7m&access_token=t4N06QPrUdoidv4uxVnNSeWDy9KlAIMXTOslCalPNRxwcUMi0AvCBsvS8HRYr186',
      'status': 200,
      'timeout': 0,
      'upload': {},
      'withCredentials': true,
    },
    'status': 200,
    'statusText': undefined,
  }
}

export const sendMetadata = async (tempId: string, metadata: object, token: string) => {
  return {
    'config': {
      'adapter': [],
      'data': '{"capturerVerbatim":["Test Testman"],"intellectualOwner":"Test Testman","intellectualRights":"MZ.intellectualRightsCC-BY-4.0","keyword":["habitaatti"]}',
      'headers': {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      },
      'maxBodyLength': -1,
      'maxContentLength': -1,
      'method': 'post',
      'params': {
        'access_token': 't4N06QPrUdoidv4uxVnNSeWDy9KlAIMXTOslCalPNRxwcUMi0AvCBsvS8HRYr186',
        'personToken': 'Pfk3NA3n6tXMSY6QJMFdWw5w2e8jvlqkiMnpqP0IEJdlgw7m',
      },
      'timeout': 0,
      'transformRequest': [
        [],
      ],
      'transformResponse': [
        [],
      ],
      'transitional': {
        'clarifyTimeoutError': false,
        'forcedJSONParsing': true,
        'silentJSONParsing': true,
      },
      'url': 'https://apitest.laji.fi/v0/images/648d13ed-de48-4372-94d9-e56e45f1c771',
      'validateStatus': [],
      'xsrfCookieName': 'XSRF-TOKEN',
      'xsrfHeaderName': 'X-XSRF-TOKEN',
    },
    'data': {
      '@context': 'http://schema.laji.fi/context/image-en.jsonld',
      'capturerVerbatim': [
        'Test Testman',
      ],
      'fullURL': 'https://imagetest.laji.fi/MM.103959/7e70e3a7-4608-4e6a-a76a-f40e48584e06.jpg',
      'id': 'MM.103959',
      'intellectualOwner': 'Test Testman',
      'intellectualRights': 'MZ.intellectualRightsCC-BY-4.0',
      'keyword': [
        'habitaatti',
      ],
      'largeURL': 'https://imagetest.laji.fi/MM.103959/7e70e3a7-4608-4e6a-a76a-f40e48584e06.jpg',
      'originalURL': 'https://imagetest.laji.fi/MM.103959/7e70e3a7-4608-4e6a-a76a-f40e48584e06.jpg',
      'squareThumbnailURL': 'https://imagetest.laji.fi/MM.103959/7e70e3a7-4608-4e6a-a76a-f40e48584e06_square.jpg',
      'thumbnailURL': 'https://imagetest.laji.fi/MM.103959/7e70e3a7-4608-4e6a-a76a-f40e48584e06_thumb.jpg',
      'uploadedBy': 'MA.1',
    }
  }
}